GET http://127.0.0.1:8080/order
Content-Type: application/json

###
GET http://127.0.0.1:8080/order/2021-05-02-15
Content-Type: application/json

###
GET http://127.0.0.1:8080/order/2021-05-02-15/total
Content-Type: application/json